version: "3.9"

services:
  todolist-app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: todolist-app
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
      - 5678:5678

  database:
    image: postgres:17.5-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: todolist-admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist-app
    volumes:
      - todolist-vol:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  todolist-vol: {}
